# Generated by Django 3.2.9 on 2021-12-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloga', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Commentm',
        ),
        migrations.AlterModelOptions(
            name='commentm',
            options={'ordering': ('created',)},
        ),
    ]
